use customer_shopping_data;
/* 
describe customer_data;
 select * from customer_data;
*/
select * from customer_data;
-- Business Insights Questions

-- 1. Which category generates highest revenue?

SELECT 
    category,
    ROUND(SUM(purchase_amount), 2) AS highest_revenue
FROM customer_data
GROUP BY category
ORDER BY highest_revenue DESC;

-- ? Business problem :-   Company does not know which category contributes more to revenue

		-- Impact
				-- Helps prioritizing high-performing category
                -- Optimize inventory planning
                -- Improve markeing ROI
-- -------------------------------------------------------------------------------------------------------------------------------------------------------

-- 2. Are discount actually increasing purchase value? 

SELECT 
	discount_applied,
    ROUND(SUM(purchase_amount), 2) AS total_revenue,
    ROUND(AVG(purchase_amount), 2) AS total_average
FROM customer_data
GROUP BY discount_applied;

-- ? Business problem:- Discounts may reduce profit without increasing sales
		-- Reduce unnecessary  discount costs
        -- Improve profit margins
-- -------------------------------------------------------------------------------------------------------------------------------------------------------
-- 3. What is the total revenue generated by male or female customer?

SELECT 
    gender,
    ROUND(SUM(purchase_amount), 2) AS highest_revenue
FROM customer_data
GROUP BY gender
ORDER BY highest_revenue DESC;

-- ? Business problem:- Lack of understanding of revenue contribution by gender segments.
		
        -- Impact:- Helps design targeted marketing campaign based on gender
        -- Enhance personalisation efforts
   
-- -------------------------------------------------------------------------------------------------------------------------------------------------------

-- 4. Which customer used a discount but still spent more then the average purchase amount?

SELECT 
	customer_id,
    purchase_amount,
    discount_applied
FROM customer_data
where discount_applied= "Yes" AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer_data)
LIMIT 10;

-- ? Business problem:- Company cannot identify high-spending customers who are also discount users.
		
        -- Impact:- 
        -- Identify premium discount-sensitive customers
        -- Improve customer retention and revenue
        -- Enables targeted discount campaign

-- -------------------------------------------------------------------------------------------------------------------------------------------------------
-- 5. Average purchase: Standard vs Express Shipping

select * from customer_data;

SELECT 
	shipping_type,
	COUNT(DISTINCT customer_id) as order_placed, 
    ROUND(AVG(purchase_amount), 2) as avg_purchase
FROM Customer_data
-- WHERE shipping_type IN('Standard', 'Express')
GROUP BY shipping_type;

-- Impact:-
		-- Helps optimize shipping pricing strategy
        -- Increase average order value 
  -- -------------------------------------------------------------------------------------------------------------------------------------------------------
      
-- 6. Do subscribed customers spend more? Compare average speed and total revenue between subscribers and non-subscribers

select * from customer_data;

SELECT 
	subscription_status, 
    ROUND(AVG(purchase_amount),2) as avg_revenue,
	ROUND(SUM(purchase_amount),2) as total_revenue
FROM customer_data
group by subscription_status;

-- Impact:- Effectiveness of subscription programs is unknown.

 -- -------------------------------------------------------------------------------------------------------------------------------------------------------

-- 7. Top 5 products with highest discount usage %

SELECT 
	item_purchased, 
    count(item_purchased) as total_item_sold,
    count(case when discount_applied='Yes' Then 1 end) as sold_when_discount_applied,
        count(case when discount_applied='Yes' Then 1 end) *100.0/ COUNT(*) as discount_percent
FROM customer_data
group by item_purchased
order by discount_percent desc
limit 5;

-- Business problem:- Some products may be overly dependent on discount
	-- Impact:-
			-- Identify discounted driven products

 -- -------------------------------------------------------------------------------------------------------------------------------------------------------
-- 8. Segment customer into new, returning and loyal based on their total number of previous purchase, and show the count of each segment

SELECT 
	CASE 
		WHEN previous_purchases = '0' Then 'New Customer'
        WHEN previous_purchases BETWEEN 1 AND 15 THEN 'Returning Customer'
	ELSE 'Loyal Customer'
END As customer_segment,
COUNT(*) as customer_count
FROM customer_data
GROUP BY CASE 
		WHEN previous_purchases = '0' Then 'New Customer'
        WHEN previous_purchases BETWEEN 1 AND 15 THEN 'Returning Customer'
	ELSE 'Loyal Customer'
END;

-- Business Problem :- Lack of customer segmentation leads to generic strategies

-- Impact:- 
			-- Enables personalized marketing
            -- Improves Retentation strategies
            -- Increase conversation rates
            
-- -------------------------------------------------------------------------------------------------------------------------------------------------------
            
-- 9. What are the top 3 most purchased products within each category?

WITH CTE as 
(
SELECT 
	category,
    item_purchased,
    COUNT(item_purchased) as most_purchased,
    RANK() OVER(PARTITION BY category ORDER BY COUNT(item_purchased) DESC) AS RNK
FROM customer_data
GROUP BY category, item_purchased
)

SELECT * from CTE
WHERE RNK < 3;

/*	Business Problem:- The company doesn't know top-performing products within categories
		IMPACT:-
				-- Improve product placement and recommendations
                -- Helps inventory optimization
*/

-- -------------------------------------------------------------------------------------------------------------------------------------------------------
-- 10. What is the revenue contribution of each age group?

SELECT 
	CASE 
		WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 35 THEN '26-35'
        WHEN age BETWEEN 36 AND 50 THEN '36-50'
        ELSE '51+'
	END AS age_group,
    ROUND(SUM(purchase_amount),2) as total_revenue
FROM customer_data
group by CASE 
		WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 35 THEN '26-35'
        WHEN age BETWEEN 36 AND 50 THEN '36-50'
        ELSE '51+'
	END
    order by total_revenue desc;





 
	